name: Deploy Motorcycle Fuel Tracker

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v2.4.2, v3.0.0, etc.
    branches:
      - main   # Also deploy on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Need write access to push to gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version info
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Tag-based deployment
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "DEPLOYMENT_TYPE=release" >> $GITHUB_ENV
          else
            # Main branch deployment
            COMMIT_HASH=$(git rev-parse --short HEAD)
            echo "VERSION=dev-$COMMIT_HASH" >> $GITHUB_ENV
            echo "DEPLOYMENT_TYPE=development" >> $GITHUB_ENV
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M UTC')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Inject version and build info into HTML
        run: |
          echo "Deploying $DEPLOYMENT_TYPE build"
          echo "Version: '$VERSION'"
          echo "Build date: '$BUILD_DATE'"
          echo "Commit: '$COMMIT_HASH'"

          # Show what we're replacing
          echo "=== BEFORE replacement ==="
          grep -n "{{VERSION}}" index.html || echo "No {{VERSION}} found"
          grep -n "{{BUILD_DATE}}" index.html || echo "No {{BUILD_DATE}} found"

          # Replace placeholders in index.html with more robust escaping
          sed -i "s/{{VERSION}}/${VERSION}/g" index.html
          sed -i "s/{{BUILD_DATE}}/${BUILD_DATE}/g" index.html
          sed -i "s/{{COMMIT_HASH}}/${COMMIT_HASH}/g" index.html

          # Verify replacements worked
          echo "=== AFTER replacement ==="
          grep -n "$VERSION" index.html || echo "Version replacement failed"
          grep -A2 -B2 "Version Footer" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: '.github,DEPLOYMENT.md,.claude'